version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./site:/var/www/html/
    ports:
      - 80:80

  db:
    image: mysql
    volumes:
      - ./db_data:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: password
        
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    